spring.application.name=Order-Service
#spring.datasource.url=jdbc:postgresql://localhost:5432/order-service
#spring.datasource.username=postgres
#spring.datasource.password=root
#spring.datasource.driver-class-name=org.postgresql.Driver


server.port=8081

# secondary datasource (MySQL)
spring.datasource.secondary.jdbc-url=jdbc:mysql://localhost:3306/orderService
spring.datasource.secondary.username=root
spring.datasource.secondary.password=Root@123
spring.datasource.secondary.driver-class-name=com.mysql.cj.jdbc.Driver



spring.datasource.primary.jdbc-url=jdbc:postgresql://localhost:5432/order-service
spring.datasource.primary.username=postgres
spring.datasource.primary.password=root
spring.datasource.primary.driver-class-name=org.postgresql.Driver

logging.level.org.springframework.cache=TRACE

spring.devtools.restart.enabled=false



#redis config
spring.cache.type=redis

spring.redis.host=localhost
spring.redis.port=6379

eureka.client.service-url.defaultZone=http://localhost:8761/eureka

#Kafka things

# Kafka Bootstrap Server
spring.kafka.bootstrap-servers=localhost:9092

# Producer settings
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

# Reliability (important for prod)
spring.kafka.producer.acks=all
spring.kafka.producer.retries=3
spring.kafka.producer.properties.enable.idempotence=true

# Topic name (externalized)
kafka.topic.booking-created=booking.created

management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.show-details=always
management.endpoint.prometheus.enabled=true
management.server.port=${server.port}



#Changes for Docker
#spring.application.name=Order-Service
#server.port=8081
#
## ---------------- MYSQL (secondary)
#spring.datasource.secondary.jdbc-url=jdbc:mysql://mysql:3306/orderService
#spring.datasource.secondary.username=root
#spring.datasource.secondary.password=Root@123
#spring.datasource.secondary.driver-class-name=com.mysql.cj.jdbc.Driver
#
## ---------------- POSTGRES (primary)
#spring.datasource.primary.jdbc-url=jdbc:postgresql://postgres:5432/order-service
#spring.datasource.primary.username=postgres
#spring.datasource.primary.password=root
#spring.datasource.primary.driver-class-name=org.postgresql.Driver
#
## ---------------- REDIS
#spring.cache.type=redis
#spring.redis.host=redis
#spring.redis.port=6379
#
## ---------------- EUREKA
#eureka.client.service-url.defaultZone=http://eureka:8761/eureka
#
## ---------------- KAFKA
#spring.kafka.bootstrap-servers=kafka:9092
#
#spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
#spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
#
#spring.kafka.producer.acks=all
#spring.kafka.producer.retries=3
#spring.kafka.producer.properties.enable.idempotence=true
#
#kafka.topic.booking-created=booking.created
#
## ---------------- Miscz
#logging.level.org.springframework.cache=TRACE
#spring.devtools.restart.enabled=false
